"""Add system_config table

Revision ID: 0bca08cd152c
Revises: 704fa583c3a3
Create Date: 2025-06-10 00:18:48.667585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bca08cd152c'
down_revision = '704fa583c3a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_key', sa.String(length=50), nullable=False, comment='配置项键名'),
    sa.Column('config_value', sa.Text(), nullable=False, comment='配置项值'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='配置项描述'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_config')
    # ### end Alembic commands ###
