"""Add book and book_category tables

Revision ID: 17ba5c25166c
Revises: 1610d959bf32
Create Date: 2025-06-09 22:09:37.475808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17ba5c25166c'
down_revision = '1610d959bf32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=50), nullable=False, comment='分类名称'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父分类ID，0表示顶级分类'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='分类描述'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False, comment='书名'),
    sa.Column('author', sa.String(length=50), nullable=False, comment='作者'),
    sa.Column('publisher', sa.String(length=50), nullable=False, comment='出版社'),
    sa.Column('isbn', sa.String(length=20), nullable=False, comment='ISBN号'),
    sa.Column('publication_date', sa.Date(), nullable=True, comment='出版日期'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True, comment='价格'),
    sa.Column('total_count', sa.Integer(), nullable=False, comment='图书总数'),
    sa.Column('available_count', sa.Integer(), nullable=False, comment='可借数量'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='图书状态，1为在架可借，2为已借出，3为已下架'),
    sa.Column('cover_image', sa.String(length=255), nullable=True, comment='封面图片路径'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='分类ID'),
    sa.ForeignKeyConstraint(['category_id'], ['book_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False,
               existing_comment='邮箱')
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True,
               existing_comment='邮箱')

    op.drop_table('book')
    op.drop_table('book_category')
    # ### end Alembic commands ###
