"""Add rejection_reason to records

Revision ID: 34d10b3d44f8
Revises: b90805a30d84
Create Date: 2025-06-12 14:42:39.390183

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34d10b3d44f8'
down_revision = 'b90805a30d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejection_reason', sa.String(length=255), nullable=True, comment='拒绝理由'))

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejection_reason', sa.String(length=255), nullable=True, comment='拒绝理由'))
        batch_op.alter_column('reservation_date',
               existing_type=mysql.DATETIME(),
               comment='预约申请日期',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('reservation_date',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='预约申请日期',
               existing_nullable=False)
        batch_op.drop_column('rejection_reason')

    with op.batch_alter_table('borrow_record', schema=None) as batch_op:
        batch_op.drop_column('rejection_reason')

    # ### end Alembic commands ###
