"""Add borrow_record table and relationships

Revision ID: 704fa583c3a3
Revises: 17ba5c25166c
Create Date: 2025-06-09 23:31:36.723734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704fa583c3a3'
down_revision = '17ba5c25166c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrow_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('book_id', sa.Integer(), nullable=False, comment='图书ID'),
    sa.Column('borrow_date', sa.DateTime(), nullable=False, comment='借阅日期'),
    sa.Column('due_date', sa.DateTime(), nullable=False, comment='应还日期'),
    sa.Column('return_date', sa.DateTime(), nullable=True, comment='实际归还日期'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='借阅状态，1为借阅中，2为已归还，3为逾期'),
    sa.Column('fine_amount', sa.Numeric(precision=10, scale=2), nullable=True, comment='逾期罚款金额'),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('borrow_record')
    # ### end Alembic commands ###
