"""Refactor borrow_record with server_default

Revision ID: 9ed16168f61f
Revises: de98921360e1
Create Date: 2025-06-11 20:50:01.399057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ed16168f61f'
down_revision = 'de98921360e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='申请日期'))
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
        batch_op.alter_column('book_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='图书ID',
               existing_nullable=False)
        batch_op.alter_column('borrow_date',
               existing_type=mysql.DATETIME(),
               nullable=True,
               comment='实际借出日期(管理员批准后填写)',
               existing_comment='借阅日期')
        batch_op.alter_column('due_date',
               existing_type=mysql.DATETIME(),
               nullable=True,
               comment='应还日期(管理员批准后计算)',
               existing_comment='应还日期')
        batch_op.alter_column('status',
               existing_type=mysql.SMALLINT(),
               comment='状态:0-借阅待批,1-借阅中,2-已归还,3-逾期归还,6-还书待批,9-借阅失败',
               existing_comment='借阅状态，1为借阅中，2为已归还，3为逾期',
               existing_nullable=False)
        batch_op.alter_column('fine_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='逾期罚款金额',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow_record', schema=None) as batch_op:
        batch_op.alter_column('fine_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='逾期罚款金额',
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.SMALLINT(),
               comment='借阅状态，1为借阅中，2为已归还，3为逾期',
               existing_comment='状态:0-借阅待批,1-借阅中,2-已归还,3-逾期归还,6-还书待批,9-借阅失败',
               existing_nullable=False)
        batch_op.alter_column('due_date',
               existing_type=mysql.DATETIME(),
               nullable=False,
               comment='应还日期',
               existing_comment='应还日期(管理员批准后计算)')
        batch_op.alter_column('borrow_date',
               existing_type=mysql.DATETIME(),
               nullable=False,
               comment='借阅日期',
               existing_comment='实际借出日期(管理员批准后填写)')
        batch_op.alter_column('book_id',
               existing_type=mysql.INTEGER(),
               comment='图书ID',
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               comment='用户ID',
               existing_nullable=False)
        batch_op.drop_column('request_date')

    # ### end Alembic commands ###
